# Generated by Django 5.2 on 2025-04-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_brand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galary',
            options={'verbose_name_plural': 'Galaries'},
        ),
        migrations.AddField(
            model_name='galary',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
