# Generated by Django 5.2 on 2025-04-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_galary_product_product_galary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='galary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.galary'),
        ),
    ]
