# Generated by Django 5.2 on 2025-04-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_galary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='galary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.galary'),
        ),
    ]
